<?php
function create_procedure($conn, $procedure_name){
  $flag="NO";
  $sql = "SHOW PROCEDURE STATUS WHERE db = 'helf';";
  $result=mysqli_query($conn,$sql) or die('Error: '.mysqli_error($conn));

  while ($row=mysqli_fetch_row($result)) {
    if($row[1] === "$procedure_name"){//문자열로 넘어오므로 ""으로 처리 ''은 문자열뿐아니라 속성도 반영
      $flag="OK";
      break;
    }
  }//end of while

  if($flag==="NO"){
    $sql="
CREATE PROCEDURE `carecenter_procedure`()
BEGIN
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','강남구','강남구보건소','보건소','강남구보건소','서울 강남구 선릉로 668','02-3423-7200');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','강동구','강동구보건소','보건소','강동구보건소','서울 강동구 성내로 45  (성내동, 강동구보건소)','02-3425-8500');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','강북구','강북구보건소','보건소','강북구보건소','서울 강북구 한천로 897','02-901-7600');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','강서구','강서구보건소','보건소','강서구보건소','서울 강서구 공항대로 561','02-2600-5800');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','관악구','관악구보건소','보건소','관악구보건소','서울 관악구 관악로 145','02-879-7010');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','광진구','광진구보건소','보건소','광진구보건소','서울 광진구 자양로 117','02-450-1360');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','구로구','구로구보건소','보건소','구로구보건소','서울 구로구 구로중앙로28길 66  (구로동, 구로구보건소)','02-860-2600');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','금천구','금천구보건소','보건소','금천구보건소','서울 금천구 시흥대로73길 70','02-2627-2423');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','노원구','노원구보건소','보건소','노원구보건소','서울 노원구 노해로 437(상계동)','02-2116-3115');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','도봉구','도봉구보건소','보건소','도봉구보건소','서울 도봉구 방학로3길 117','02-2091-4600');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','동대문구','동대문구보건소','보건소','동대문구보건소','서울 동대문구 천호대로 145 동대문구보건소 (용두동, 동대문구청)','02-2127-5400');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','동작구','동작구보건소','보건소','동작구보건소','서울 동작구 장승배기로10길 42  (상도동, 동작문화복지센타)','02-820-1439');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','마포구','마포구보건소','보건소','마포구보건소','서울 마포구 월드컵로 212, 마포구보건소  (성산동, 마포구청)','02-3153-9020');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','서대문구','서대문구보건소','보건소','서대문구보건소','서울 서대문구 연희로 242, 서대문구청별관  (연희동, 서대문구보건소)','02-330-1801');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','서초구','서초구보건소','보건소','서초구보건소','서울 서초구 남부순환로 2584, 보건소  (서초동, 서초구청)','02-2155-8114');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','성동구','성동구보건소','보건소','성동구보건소','서울 성동구 마장로23길 10','02-2286-7011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','성북구','성북구보건소','보건소','성북구보건소','서울 성북구 화랑로 63  (하월곡동, 성북구보건소)','02-2241-1749');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','송파구','송파구보건소','보건소','송파구보건소','서울 송파구 올림픽로 326','02-2147-3420');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','양천구','양천구보건소','보건소','양천구보건소','서울 양천구 목동서로 339','02-2620-4340');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','영등포구','영등포구보건소','보건소','영등포구보건소','서울 영등포구 당산로 123  (당산동3가)','02-2670-4896');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','용산구','용산구보건소','보건소','용산구보건소','서울 용산구 녹사평대로 150 용산보건소 (이태원동, 용산구종합행정타운)','02-2199-8020');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','은평구','은평구보건소','보건소','은평구보건소','서울 은평구 은평로 195, 은평구보건소  (녹번동)','02-351-8152');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','종로구','종로구보건소','보건소','종로구보건소','서울 종로구 자하문로19길 36  (옥인동, 종로구보건소, 청운효자동자치회관)','02-2148-3514');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','중구','중구보건소','보건소','중구보건소','서울 중구 다산로39길 16','02-3396-6317');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('서울','중랑구','중랑구보건소','보건소','중랑구보건소','서울 중랑구 봉화산로 179  (신내동, 중랑구청)','02-2094-0710');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','강서구','강서구보건소','보건소','강서구보건소','부산 강서구 공항로811번길 10  (대저2동, 강서브라이트센터)','051-970-3415');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','금정구','금정구보건소','보건소','금정구보건소','부산 금정구 중앙대로 1777, 보건소  (부곡동, 금정구청)','051-519-5051');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','기장군','기장군보건소','보건소','기장군보건소','부산 기장군 기장읍 기장대로 560 기장군보건소','051-709-4791');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','남구','남구보건소','보건소','남구보건소','부산 남구 못골로 23  (대연동, 남구보건소)','051-607-6460');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','동구','동구보건소','보건소','동구보건소','부산 동구 구청로 1','051-440-6500');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','동래구','동래구보건소','보건소','동래구보건소','부산 동래구 명륜로187번길 56  (명륜동, 동래구보건소)','051-550-6700');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','부산진구','부산진구보건소','보건소','부산진구보건소','부산 부산진구 황령대로8번길 36  (범천동, 부산진구보건소)','051-645-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','북구','북구보건소','보건소','북구보건소','부산 북구 금곡대로 348, 북구보건소  (화명동, 북구보건소)','051-309-4500');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','사상구','사상구보건소','보건소','사상구보건소','부산 사상구 학감대로 242 사상구보건소 (감전동, 사상구청)','051-310-4791');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','사하구','사하구보건소','보건소','사하구보건소','부산 사하구 하신번영로127번길 2  (신평동)','051-220-5701');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','서구','서구보건소','보건소','서구보건소','부산 서구 부용로 30 (부용동2가, 서구보건소 부민노인복지관)','051-240-4851');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','수영구','수영구보건소','보건소','수영구보건소','부산 수영구 수영로 637-5, 본관  (광안동, 수영구 보건소)','051-610-5601');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','연제구','연제구보건소','보건소','연제구보건소','부산 연제구 연제로 2   (연산동, 연제구 보건소)','051-665-4791');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','영도구','영도구보건소','보건소','영도구보건소','부산 영도구 태종로 423','051-416-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','중구','중구보건소','보건소','중구보건소','부산 중구 중구로 120','051-600-4741');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('부산','해운대구','해운대구보건소','보건소','해운대구보건소','부산 해운대구 양운로37번길 59  (좌동, 해운대구보건소)','051-746-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','남구','남구보건소','보건소','남구보건소','대구 남구 영선길 34, 보건의료서비스센터  (대명동, 남구 보건소)','053-664-3601');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','달서구','달서구보건소','보건소','달서구보건소','대구 달서구 와룡로49길 30  (죽전동, 달서구보건소)','053-667-5618');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','달성군','달성군 보건소','보건소','달성군 보건소','대구 달성군 현풍면 비슬로130길 17 달성군보건소 (달성군보건소)','053-668-3101');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','동구','동구보건소','보건소','동구보건소','대구 동구 동촌로 79(검사동)','053-662-3201');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','북구','북구보건소','보건소','북구보건소','대구 북구 성북로 49','053-665-3211');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','서구','서구보건소','보건소','서구보건소','대구 서구 국채보상로 257','053-663-3111');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','수성구','수성구보건소','보건소','수성구보건소','대구 수성구 수성로 213  (중동)','053-666-3111');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대구','중구','중구보건소','보건소','중구보건소','대구 중구 태평로 45 중구보건소 (태평로3가, 중구보건소)','053-661-3121');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','강화군','강화군보건소','보건소','강화군보건소','인천 강화군 강화읍 충렬사로 26-1','032-930-4013');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','계양구','계양구보건소','보건소','계양구보건소','인천 계양구 계산새로 88','032-430-7801');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','남구','남구보건소','보건소','남구보건소','인천 남구 주안서로 25','032-880-5310');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','남동구','남동구보건소','보건소','남동구보건소','인천 남동구 소래로 633','032-464-4001');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','동구','동구보건소','보건소','동구보건소','인천 동구 석수로 90','032-762-4001');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','부평구','부평구보건소','보건소','부평구보건소','인천 부평구 부흥로 291','032-509-8200');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','서구','서구보건소','보건소','서구보건소','인천 서구 탁옥로 39','032-560-5000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','연수구','연수구보건소','보건소','연수구보건소','인천 연수구 함박뫼로 13','032-749-8000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','옹진군','옹진군보건소','보건소','옹진군보건소','인천 남구 매소홀로 120','032-899-3120');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('인천','중구','중구보건소','보건소','중구보건소','인천 중구 참외전로72번길 21  (전동, 중구보건소,미추홀문화센터)','032-760-6010');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('광주','광산구','광산구보건소','보건소','광산구보건소','광주 광산구 광산로29번길 15','062-960-8733');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('광주','남구','남구보건소','보건소','남구보건소','광주 남구 봉선로 1  (주월동, 남구청)','062-607-4311');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('광주','동구','동구보건소','보건소','동구보건소','광주 동구 서남로 1 ','062-608-3261');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('광주','북구','북구보건소','보건소','북구보건소','광주 북구 우치로 65','062-410-8961');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('광주','서구','서구보건소','보건소','서구보건소','광주 서구 경열로 33 서구보건소 (농성동, 서구청)','062-350-4108');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대전','대덕구','대덕구보건소','보건소','대덕구보건소','대전 대덕구 석봉로38번길 55','042-608-5499');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대전','동구','동구보건소','보건소','동구보건소','대전 동구 동구청로 147','042-251-6111');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대전','서구','서구보건소','보건소','서구보건소','대전 서구 만년로 74  (만년동, 대전서구보건소)','042-288-4500');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대전','유성구','유성구보건소','보건소','유성구보건소','대전 유성구 유성대로730번길 51','042-611-5011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('대전','중구','중구보건소','보건소','중구보건소','대전 중구 산성로 63  (문화동, 중구보건소)','042-580-2700');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('울산','남구','남구보건소','보건소','남구보건소','울산 남구 삼산중로 132','052-226-2805');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('울산','동구','동구보건소','보건소','동구보건소','울산 동구 봉수로 155(화정동)','052-209-4080');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('울산','북구','북구보건소','보건소','북구보건소','울산 북구 산업로 1018  (연암동, 보건소)','052-289-3450');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('울산','울주군','울주군보건소','보건소','울주군보건소','울산 울주군 삼남면 서향교1길 67-12','052-204-2798');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('울산','중구','중구보건소','보건소','중구보건소','울산 중구 외솔큰길 225, 중구보건소  (남외동, 중구보건소)','052-211-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('세종','세종특별자치시','세종특별자치시보건소','보건소','세종특별자치시보건소','세종 조치원읍 건강길 16  (세종특별자치시보건소)','044-301-2000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','가평군','가평군보건소','보건소','가평군보건소','경기 가평군 가평읍 가화로 155-18  (가평군보건소)','031-582-2488');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','고양시','고양시 덕양구보건소','보건소','고양시 덕양구보건소','경기 고양시 덕양구 원당로33번길 28  (주교동, 덕양구보건소)','031-966-9317');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','고양시','고양시 일산동구보건소','보건소','고양시 일산동구보건소','경기 고양시 일산동구 중앙로 1228 1,2층 (마두동, KT고양지사)','031-8075-4084');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','고양시','고양시 일산서구보건소','보건소','고양시 일산서구보건소','경기 고양시 일산서구 일중로 54','031-8075-4160');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','과천시','과천시보건소','보건소','과천시보건소','경기 과천시 관문로 69','02-2150-3800');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','광명시','광명시보건소','보건소','광명시보건소','경기 광명시 오리로 613 광명시보건소 (하안동, 광명시보건소)','02-2680-2862');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','광주시','광주시보건소','보건소','광주시보건소','경기 광주시 파발로 194  (경안동, 광주시보건소)','031-760-2110');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','구리시','구리시보건소','보건소','구리시보건소','경기 구리시 건원대로34번길 84  (인창동, 구리보건소)','031-550-8681');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','군포시','군포시보건소','보건소','군포시보건소','경기 군포시 군포로 221','031-461-5464');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','김포시','김포시보건소','보건소','김포시보건소','경기 김포시 사우중로 108','031-980-5011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','남양주시','남양주보건소','보건소','남양주보건소','경기 남양주시 경춘로 1037, 남양주보건소  (금곡동, 남양주시청제1청사)','031-590-2552');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','남양주시','남양주풍양보건소','보건소','남양주풍양보건소','경기 남양주시 진접읍 해밀예당1로 30-39, 북부종합보건복지타운  ','031-590-4771');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','동두천시','동두천시보건소','보건소','동두천시보건소','경기 동두천시 중앙로 167  (생연동, 동두천시보건소)','031-860-3373');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','부천시','부천시보건소','보건소','부천시보건소','경기 부천시 옥산로10번길 16  (중동, 부천시보건소)','032-625-4193');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','성남시','성남시 분당구보건소','보건소','성남시 분당구보건소','경기 성남시 분당구 양현로 306  (야탑동, 분당보건소)','031-729-3990');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','성남시','성남시 수정구보건소','보건소','성남시 수정구보건소','경기 성남시 수정구 수정로 218  (신흥동, 수정구보건소)','031-729-3870');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','성남시','성남시 중원구보건소','보건소','성남시 중원구보건소','경기 성남시 중원구 금상로 137 중원구보건소 (상대원동, 중원구보건소)','031-729-3893');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','수원시','수원시 권선구보건소','보건소','수원시 권선구보건소','경기 수원시 권선구 호매실로 22-50 권선구보건소 (탑동, 권선구보건소)','031-228-6583');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','수원시','수원시 영통구보건소','보건소','수원시 영통구보건소','경기 수원시 영통구 영통로 396  (영통동, 영통구보건소)','031-228-8716');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','수원시','수원시 장안구보건소','보건소','수원시 장안구보건소','경기 수원시 장안구 송원로 101','031-228-5802');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','수원시','수원시 팔달구보건소','보건소','수원시 팔달구보건소','경기 수원시 팔달구 팔달산로 6 팔달구보건소 (교동, 팔달구 보건소)','031-227-7617');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','시흥시','시흥시보건소','보건소','시흥시보건소','경기 시흥시 호현로 55, 주차장 시흥시보건소 (대야동, 시흥시보건소대야종합사회복지관)','031-310-5811');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','안산시','안산시 단원구보건소','보건소','안산시 단원구보건소','경기 안산시 단원구 화랑로 250 단원보건소 (초지동)','031-481-3462');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','안산시','안산시 상록수보건소','보건소','안산시 상록수보건소','경기 안산시 상록구 차돌배기로1길 5  (사동, 상록수보건소)','031-481-5909');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','안성시','안성시보건소','보건소','안성시보건소','경기 안성시 강변로74번길 18','031-678-5710');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','안양시','안양시 동안구보건소','보건소','안양시 동안구보건소','경기 안양시 동안구 평촌대로253번길 41  (비산동, 동안구보건소)','031-8045-4472');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','안양시','안양시 만안구보건소','보건소','안양시 만안구보건소','경기 안양시 만안구 문예로 48  (안양동, 만안구보건소)','031-8045-3472');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','양주시','양주시보건소','보건소','양주시보건소','경기 양주시 부흥로 1533, 양주시보건소 (남방동, 양주시보건소)','031-8082-7106');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','양평군','양평군보건소','보건소','양평군보건소','경기 양평군 양평읍 마유산로 17, 양평군보건소','031-770-3505');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','여주시','여주시보건소','보건소','여주시보건소','경기 여주시 여흥로160번길 14  (상동, 여주시보건소)','031-887-3601');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','오산시','오산시보건소','보건소','오산시보건소','경기 오산시 경기동로 59','031-8036-6025');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','용인시','용인시 기흥구보건소','보건소','용인시 기흥구보건소','경기 용인시 기흥구 신갈로58번길 11','031-324-6911');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','용인시','용인시 수지구보건소','보건소','용인시 수지구보건소','경기 용인시 수지구 포은대로 435','031-324-8940');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','용인시','용인시 처인구보건소','보건소','용인시 처인구보건소','경기 용인시 처인구 중부대로 1199, 보건소  (삼가동, 용인시청)','031-324-4911');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','의왕시','의왕시보건소','보건소','의왕시보건소','경기 의왕시 오봉로 34 의왕시보건소','031-345-3541');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','의정부시','의정부시보건소','보건소','의정부시보건소','경기 의정부시 범골로 131  (의정부동, 의정부시보건소)','031-870-6001');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','이천시','이천시보건소','보건소','이천시보건소','경기 이천시 증신로153번길 13  (증포동, 이천시보건소)','031-635-2400');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','파주시','파주시보건소','보건소','파주시보건소','경기 파주시 후곡로 13 13 (금촌동, 파주시보건소)','031-940-4800');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','평택시','평택시 송탄보건소','보건소','평택시 송탄보건소','경기 평택시 서정로 295 북부보건복지센터  (서정동, 송탄보건소)','031-8024-6615');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','평택시','평택시 평택보건소','보건소','평택시 평택보건소','경기 평택시 평택5로 56','031-8024-5559');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','포천시','포천시보건소','보건소','포천시보건소','경기 포천시 포천로 1612','031-538-3600');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','하남시','하남시보건소','보건소','하남시보건소','경기 하남시 대청로 10','031-790-6555');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','화성시','화성시보건소','보건소','화성시보건소','경기 화성시 향남읍 3.1만세로 1055  (화성시보건소)','031-369-2551');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','강릉시','강릉시보건소','보건소','강릉시보건소','강원 강릉시 남부로17번길 38','033-660-3011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','고성군','고성군보건소','보건소','고성군보건소','강원 고성군 간성읍 수성로 30 고성군보건소 (보건소)','033-681-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','동해시','동해시보건소','보건소','동해시보건소','강원 동해시 천곡로 100-2  (천곡동, 보건소)','033-530-2401');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','삼척시','삼척시보건소','보건소','삼척시보건소','강원 삼척시 척주로 76','033-572-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','속초시','속초시보건소','보건소','속초시보건소','강원 속초시 수복로 36','033-631-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','양구군','양구군보건소','보건소','양구군보건소','강원 양구군 양구읍 관공서로 42  (양구군보건소)','033-481-2400');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','양양군','양양군보건소','보건소','양양군보건소','강원 양양군 양양읍 양양로 9-5','033-670-2550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','영월군','영월군보건소','보건소','영월군보건소','강원 영월군 영월읍 하송로 44','033-370-2550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','원주시','원주시보건소','보건소','원주시보건소','강원 원주시 원일로 139','033-737-4011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','인제군','인제군보건소','보건소','인제군보건소','강원 인제군 인제읍 인제로140번길 34','033-461-2425');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','정선군','정선군보건소','보건소','정선군보건소','강원 정선군 정선읍 녹송로 33','033-562-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','철원군','철원군보건소','보건소','철원군보건소','강원 철원군 갈말읍 군탄로8번길 16  ','033-450-5550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','춘천시','춘천시보건소','보건소','춘천시보건소','강원 춘천시 중앙로 135','033-250-3550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','태백시','태백시보건소','보건소','태백시보건소','강원 태백시 태백로 905','033-552-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','홍천군','홍천군보건소','보건소','홍천군보건소','강원 홍천군 홍천읍 신장대로 5','033-430-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','횡성군','횡성군보건소','보건소','횡성군보건소','강원 횡성군 횡성읍 횡성로  379 (횡성보건소)','033-340-5612');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','괴산군','괴산군보건소','보건소','괴산군보건소','충북 괴산군 괴산읍 동진천길 43  (괴산군보건소)','043-832-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','단양군','단양군보건소','보건소','단양군보건소','충북 단양군 단양읍 삼봉로 53  (단양군 보건소)','043-420-3201');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','보은군','보은군보건소','보건소','보은군보건소','충북 보은군 보은읍 동광길 50','043-540-5600');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','영동군','영동군보건소','보건소','영동군보건소','충북 영동군 영동읍 반곡동길 7, 건강증진센터  (영동군보건소)','043-740-5581');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','옥천군','옥천군보건소','보건소','옥천군보건소','충북 옥천군 옥천읍 삼양로8길 10','043-730-2114');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','음성군','음성군보건소','보건소','음성군보건소','충북 음성군 음성읍 중앙로 49  (음성보건소)','043-872-2136');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','제천시','제천시보건소','보건소','제천시보건소','충북 제천시 의림대로 242','043-641-2720');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','증평군','증평군보건소','보건소','증평군보건소','충북 증평군 증평읍 보건복지로 64-1','043-835-4220');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','진천군','진천군보건소','보건소','진천군보건소','충북 진천군 진천읍 중앙북1길 11-8, 본관  (진천군보건소)','043-539-7771');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','청주시','청주시 상당보건소','보건소','청주시 상당보건소','충북 청주시 상당구 남일면 단재로 480','043-201-3117');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','청주시','청주시 서원보건소','보건소','청주시 서원보건소','충북 청주시 서원구 사직대로 227 지하1층 (사직동, 서원구청)','043-201-3217');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','청주시','청주시 청원보건소','보건소','청주시 청원보건소','충북 청주시 청원구 오창읍 과학산업3로 238','043-201-3421');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','청주시','청주시 흥덕보건소','보건소','청주시 흥덕보건소','충북 청주시 상당구 대성로172번길 21','043-201-3391');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충북','충주시','충주시보건소','보건소','충주시보건소','충북 충주시 으뜸로 21, 본관동  (금릉동, 충주시청)','043-850-3411');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','계룡시','계룡시보건소','보건소','계룡시보건소','충남 계룡시 장안로 54','042-840-3567');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','공주시','공주시보건소','보건소','공주시보건소','충남 공주시 봉황로 123  (교동, 보건소)','041-840-8755');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','금산군','금산군보건소','보건소','금산군보건소','충남 금산군 금산읍 금산로 1559 (금산군보건소)','041-750-4311');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','논산시','논산시보건소','보건소','논산시보건소','충남 논산시 논산대로 382','041-746-8011');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','당진시','당진시보건소','보건소','당진시보건소','충남 당진시 서부로 56, 당진시보건소  (채운동, 당진시보건소)','041-360-6003');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','보령시','보령시보건소','보건소','보령시보건소','충남 보령시 남포면 보령남로 234','041-930-4199');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','부여군','부여군보건소','보건소','부여군보건소','충남 부여군 부여읍 성왕로 205','041-835-2151');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','서산시','서산시보건소','보건소','서산시보건소','충남 서산시 호수공원6로 6  (예천동, 서산시보건소)','041-667-6550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','서천군','서천군보건소','보건소','서천군보건소','충남 서천군 서천읍 사곡길 26','041-950-6700');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','아산시','아산시보건소','보건소','아산시보건소','충남 아산시 번영로224번길 20  (모종동, 아산시보건소)','041-537-3419');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','예산군','예산군보건소','보건소','예산군보건소','충남 예산군 예산읍 아리랑로 147 (예산군보건소)','041-339-8993');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','천안시','천안시 동남구보건소','보건소','천안시 동남구보건소','충남 천안시 동남구 버들로 34 동남구보건소 (문화동)','041-521-2650');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','천안시','천안시 서북구보건소','보건소','천안시 서북구보건소','충남 천안시 서북구 번영로 156','041-521-2552');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','홍성군','홍성군보건소','보건소','홍성군보건소','충남 홍성군 홍성읍 문화로 106 홍성군보건소 (홍성군보건소)','041-632-2588');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','고창군','고창군보건소','보건소','고창군보건소','전북 고창군 고창읍 전봉준로 90','063-560-8711');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','군산시','군산시보건소','보건소','군산시보건소','전북 군산시 수송동로 58  (군산시 보건소)','063-462-4923');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','김제시','김제시보건소','보건소','김제시보건소','전북 김제시 성산길 138','063-547-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','남원시','남원시보건소','보건소','남원시보건소','전북 남원시 요천로 1285','063-625-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','부안군','부안군보건소','보건소','부안군보건소','전북 부안군 부안읍 오리정로 124  (부안군보건소)','063-584-1261');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','완주군','완주군보건소','보건소','완주군보건소','전북 완주군 삼례읍 삼봉로 215-20','063-290-3003');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','익산시','익산시보건소','보건소','익산시보건소','전북 익산시 무왕로 975','063-859-4802');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','전주시','전주시 보건소','보건소','전주시 보건소','전북 전주시 완산구 전라감영로 33','063-281-6200');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','정읍시','정읍시보건소','보건소','정읍시보건소','전북 정읍시 수성1로 61, 보건소  (수성동, 정읍보건소)','063-539-6072');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','진안군','진안군보건소','보건소','진안군보건소','전북 진안군 진안읍 진무로 1189','063-430-8560');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','강진군','강진군보건소','보건소','강진군보건소','전남 강진군 강진읍 목리길 11  (강진군보건소)','061-430-3533');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','고흥군','고흥군보건소','보건소','고흥군보건소','전남 고흥군 고흥읍 등암3길 5','061-830-5561');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','광양시','광양시보건소','보건소','광양시보건소','전남 광양시 광양읍 인덕로 1100(광양시보건소)','061-797-4004');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','나주시','나주시보건소','보건소','나주시보건소','전남 나주시 풍물시장2길 57-32  (이창동, 나주시보건소)','061-339-2171');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','담양군','담양군보건소','보건소','담양군보건소','전남 담양군 담양읍 완동길 10-11  ','061-383-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','목포시','목포시보건소','보건소','목포시보건소','전남 목포시 원산로45번길 5','061-277-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','무안군','무안군보건소','보건소','무안군보건소','전남 무안군 무안읍 무안로 530','061-450-5014');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','보성군','보성군보건소','보건소','보성군보건소','전남 보성군 보성읍 송재로 153 보성군 보건소 ','061-853-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','순천시','순천시보건소','보건소','순천시보건소 ','전남 순천시 중앙로 232','061-749-6905');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','신안군','신안군보건소','보건소','신안군보건소','전남 신안군 압해읍 천사로 1004','061-243-8550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','여수시','여수시보건소','보건소','여수시보건소','전남 여수시 시청서4길 47, 여수시 보건소  (학동)','061-683-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','영광군','영광군보건소','보건소','영광군보건소','전남 영광군 영광읍 신남로4길 17','061-350-5552');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','영암군','영암군보건소','보건소','영암군보건소','전남 영암군 영암읍 오리정길 39','061-470-6525');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','장성군','장성군보건소','보건소','장성군보건소','전남 장성군 장성읍 청운11길 13  (보건소)','061-390-7550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','장흥군','장흥군보건소','보건소','장흥군보건소','전남 장흥군 장흥읍 흥성로 49','061-860-0550');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','진도군','진도군보건소','보건소','진도군보건소','전남 진도군 진도읍 남동1길 40-9','061-540-6005');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','함평군','함평군보건소','보건소','함평군보건소','전남 함평군 함평읍 중앙길 54-8   (함평보건소)','061-320-2405');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','해남군','해남군보건소','보건소','해남군보건소','전남 해남군 해남읍 해남로 46','061-531-3738');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','화순군','화순군보건소','보건소','화순군보건소','전남 화순군 화순읍 쌍충로 62','061-379-5305');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','경산시','경산시보건소','보건소','경산시보건소','경북 경산시 남매로 158  (중방동, 경산시보건소)','053-810-6310');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','경주시','경주시보건소','보건소','경주시보건소','경북 경주시 양정로 300','054-779-8577');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','고령군','고령군보건소','보건소','고령군보건소','경북 고령군 대가야읍 왕릉로 56-5 고령군보건소','054-954-1300');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','구미시','구미시 구미보건소','보건소','구미시 구미보건소','경북 구미시 선산대로 111','054-480-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','구미시','구미시 선산보건소','보건소','구미시 선산보건소','경북 구미시 선산읍 선주로 121','054-480-4151');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','군위군','군위군보건소','보건소','군위군보건소','경북 군위군 군위읍 군청로 70','054-380-7401');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','김천시','김천시보건소','보건소','김천시보건소','경북 김천시 시청1길 221','054-433-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','문경시','문경시보건소','보건소','문경시보건소','경북 문경시 점촌1길 9','054-555-2033');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','봉화군','봉화군보건소','보건소','봉화군보건소','경북 봉화군 봉화읍 봉화로 1203','054-673-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','상주시','상주시보건소','보건소','상주시보건소','경북 상주시 중앙로 111','054-535-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','성주군','성주군보건소','보건소','성주군보건소','경북 성주군 성주읍 성밖숲길 12  (성주군보건소,건강증진센터)','054-933-2400');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','안동시','안동시보건소','보건소','안동시보건소','경북 안동시 서동문로 165','054-855-5986');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','영덕군','영덕군보건소','보건소','영덕군보건소','경북 영덕군 영덕읍 경동로 8367 영덕군보건소 (영덕군보건소)','054-730-6823');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','영양군','영양군보건소','보건소','영양군보건소','경북 영양군 영양읍 동서대로 82','054-680-5114');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','영주시','영주시보건소','보건소','영주시보건소','경북 영주시 시청로1번길 19  (휴천동, 영주시보건소)','054-631-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','영천시','영천시보건소','보건소','영천시보건소','경북 영천시 옛군청1길 31','054-330-7860');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','예천군','예천군보건소','보건소','예천군보건소','경북 예천군 예천읍 충효로 424','054-650-2308');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','울진군','울진군보건소','보건소','울진군보건소','경북 울진군 울진읍 읍내8길 61-8  (울진군보건소)','054-789-5000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','의성군','의성군보건소','보건소','의성군보건소','경북 의성군 의성읍 구봉길 228','054-830-6660');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','청도군','청도군보건소','보건소','청도군보건소','경북 청도군 화양읍 청화로 79-11','054-370-6470');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','칠곡군','칠곡군보건소','보건소','칠곡군보건소','경북 칠곡군 왜관읍 관문로1길 30','054-973-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','포항시','포항시 남구보건소','보건소','포항시 남구보건소','경북 포항시 남구 동해안로 6119  (인덕동, 남구보건소)','054-270-4004');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','포항시','포항시 북구보건소','보건소','포항시 북구보건소','경북 포항시 북구 삼흥로 98(장성동)','054-270-4114');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','거제시','거제시보건소','보건소','거제시보건소','경남 거제시 수양로 506','055-639-6200');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','거창군','거창군보건소','보건소','거창군보건소','경남 거창군 거창읍 거함대로 3079 거창군보건소 (보건소)','055-940-8380');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','고성군','고성군보건소','보건소','고성군보건소','경남 고성군 고성읍 남포로79번길 103-3','055-670-4001');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','김해시','김해시보건소','보건소','김해시보건소','경남 김해시 분성로 227','055-330-4451');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','남해군','남해군보건소','보건소','남해군보건소','경남 남해군 남해읍 선소로 6','055-860-8701');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','밀양시','밀양시보건소','보건소','밀양시보건소','경남 밀양시 삼문중앙로 41 (삼문동, 밀양시보건소)','055-359-7020');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','사천시','사천시보건소','보건소','사천시보건소','경남 사천시 용현면 시청로 77 ','055-831-3560');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','양산시','양산시보건소','보건소','양산시보건소','경남 양산시 삽량로 169','055-380-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','의령군','의령군보건소','보건소','의령군보건소','경남 의령군 의령읍 의병로8길 16','055-570-4010');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','진주시','진주시보건소','보건소','진주시보건소','경남 진주시 월아산로 2026 1층 (초전동)','055-741-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','창녕군','창녕군보건소','보건소','창녕군보건소','경남 창녕군 창녕읍 우포2로 1189-35','055-530-6202');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','창원시','창원시 마산보건소','보건소','창원시 마산보건소','경남 창원시 마산합포구 월영동북로 15','055-225-5931');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','창원시','창원시 진해보건소','보건소','창원시 진해보건소','경남 창원시 진해구 진해대로 1101(풍호동) 진해보건소','055-225-6101');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','창원시','창원시 창원보건소','보건소','창원시 창원보건소','경남 창원시 의창구 중앙대로162번길 9  (신월동, 창원보건소)','055-225-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','통영시','통영시보건소','보건소','통영시보건소','경남 통영시 안개4길 108 (무전동, 통영시보건소)','055-650-6010');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','하동군','하동군보건소','보건소','하동군보건소','경남 하동군 하동읍 군청로 31  (하동보건소)','055-882-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','함안군','함안군보건소','보건소','함안군보건소','경남 함안군 가야읍 중앙남4길 10  (함안군보건소)','055-580-3100');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','함양군','함양군보건소','보건소','함양군보건소','경남 함양군 함양읍 한들로 141','055-960-5331');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','합천군','합천군보건소','보건소','합천군보건소','경남 합천군 합천읍 동서로 39','055-930-3681');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','서귀포시','서귀포시 동부보건소','보건소','서귀포시 동부보건소','제주 서귀포시 남원읍 태위로 527','064-760-6834');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','서귀포시','서귀포시 서귀포보건소','보건소','서귀포시 서귀포보건소','제주 서귀포시 중앙로101번길 52, 본관  (서홍동, 서귀포보건소)','064-760-6832');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','서귀포시','서귀포시 서부보건소','보건소','서귀포시 서부보건소','제주 서귀포시 대정읍 최남단해안로15번길 12','064-760-6251');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','제주시','제주시 동부보건소','보건소','제주시 동부보건소','제주 제주시 구좌읍 김녕로14길 6  (동부보건소)','064-728-4172');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','제주시','제주시 서부보건소','보건소','제주시 서부보건소','제주 제주시 한림읍 강구로 5 ','064-728-4111');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('제주','제주시','제주시 제주보건소','보건소','제주시 제주보건소','제주 제주시 연삼로 264  (도남동, 제주보건소)','064-728-4100');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경기','연천군','연천군보건의료원','보건의료원','연천군보건의료원','경기 연천군 전곡읍 은대성로 95','031-839-4001');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','평창군','평창군보건의료원','보건의료원','평창군보건의료원','강원 평창군 평창읍 종부로 61','033-332-4000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('강원','화천군','화천군보건의료원','보건의료원','화천군보건의료원','강원 화천군 화천읍 강변로 111, 화천보건의료원  (화천군보건의료원)','033-442-4424');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','청양군','청양군보건의료원','보건의료원','청양군보건의료원','충남 청양군 청양읍 칠갑산로7길 54','041-940-4515');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('충남','태안군','태안군보건의료원','보건의료원','태안군보건의료원','충남 태안군 태안읍 서해로 1952-16 태안군보건의료원 (태안군보건의료원)','041-671-5300');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','무주군','무주군보건의료원','보건의료원','무주군보건의료원','전북 무주군 무주읍 한풍루로 413','063-320-8314');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','순창군','순창군보건의료원','보건의료원','순창군보건의료원','전북 순창군 순창읍 교성로 135  (순창군보건의료원)','063-650-5383');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','임실군','임실군보건의료원','보건의료원','임실군보건의료원','전북 임실군 임실읍 호국로 1680','063-640-3101');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전북','장수군','장수군보건의료원','보건의료원','장수군보건의료원','전북 장수군 장수읍 장천로 247','063-351-8000');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','곡성군','곡성군보건의료원','보건의료원','곡성군보건의료원','전남 곡성군 곡성읍 곡성로 854','061-362-5060');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','구례군','구례군보건의료원','보건의료원','구례군보건의료원','전남 구례군 구례읍 동편제길 30','061-780-2003');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('전남','완도군','완도군보건의료원','보건의료원','완도군보건의료원','전남 완도군 완도읍 농공단지길 34','061-550-6720');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','울릉군','울릉군보건의료원','보건의료원','울릉군보건의료원','경북 울릉군 울릉읍 울릉순환로 396-18','054-790-6813');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경북','청송군','청송군보건의료원','보건의료원','청송군보건의료원','경북 청송군 청송읍 의료원길 19  (청송보건의료원)','054-870-7200');
INSERT INTO `carecenter` (`city`,`area`,`area_health`,`type`,`name`,`address`,`tel`) VALUES ('경남','산청군','산청군보건의료원','보건의료원','산청군보건의료원','경남 산청군 산청읍 중앙로 97  (산청군보건의료원)','055-970-7500');
END";

    if(mysqli_query($conn,$sql)){
      echo "<script>alert('$procedure_name 프로시저가 생성되었습니다.');</script>";
      call_procedure($conn, $procedure_name);
    }else{
      echo "프로시저 생성 중 실패원인".mysqli_error($conn);
    }
  }//end of if flag

}//end of function
function call_procedure($conn, $procedure_name){
    $sql = "call ". $procedure_name.";";
  $result=mysqli_query($conn,$sql) or die('Error: '.mysqli_error($conn));
  if($result){
    echo "<script>alert('$procedure_name 프로시저가 정상적으로 작동되었습니다.');</script>";
  }else{
    echo "프로시저 작동 중 실패원인".mysqli_error($conn);
  }
}
?>
